#!/usr/bin/env python3
"""Generate a bounded Markdown inventory of GGUF metadata.

The module is usable both as a standalone script and by the Qt Diagnose flow.
It shares AutoTuner's dependency-free GGUF reader, persistent stat cache, and
bounded parallel header scan; model tensor data is never loaded.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
from typing import Callable, Dict, Iterable, List, Optional, Tuple

from scanner import (
    flush_gguf_metadata_cache,
    read_gguf_metadata_many,
)

ProgressCallback = Callable[[int, int, str], None]


def discover_gguf_files(roots: Iterable[Path]) -> List[Path]:
    """Return unique GGUF files below existing roots in deterministic order."""
    files: List[Path] = []
    seen: set[str] = set()
    for raw_root in roots:
        root = Path(raw_root).expanduser()
        if not root.is_dir():
            continue
        try:
            candidates = sorted(root.rglob("*.gguf"), key=lambda p: str(p).casefold())
        except (OSError, PermissionError):
            continue
        for path in candidates:
            try:
                key = os.path.normcase(str(path.resolve(strict=False)))
            except (OSError, RuntimeError):
                key = os.path.normcase(str(path))
            if key in seen:
                continue
            seen.add(key)
            files.append(path)
    return files


def _relative_label(path: Path, roots: List[Path]) -> str:
    for root in roots:
        try:
            relative = path.relative_to(root)
        except ValueError:
            continue
        if len(roots) > 1:
            return str(Path(root.name) / relative)
        return str(relative)
    return path.name


def _render_value(value: object) -> str:
    if value is None:
        return "<large array omitted by bounded reader>"
    if isinstance(value, str):
        return value
    return repr(value)


def _escape_table(value: str) -> str:
    return value.replace("|", "\\|").replace("\r", " ").replace("\n", " ")


def format_metadata_markdown(
    files: List[Path],
    metadata_by_path: Dict[Path, Dict[str, object]],
    roots: Iterable[Path],
) -> str:
    """Format already-read metadata without exposing absolute root paths."""
    normalized_roots = [Path(root).expanduser().resolve(strict=False) for root in roots]
    lines = [
        "# GGUF model metadata inventory",
        "",
        (
            "Generated by AutoTuner's bounded header reader. Tensor payloads and "
            "prompts are not included; paths are root-relative. GGUF metadata can "
            "still contain converter-supplied provenance strings, so review this "
            "inventory before sharing it."
        ),
        "",
        f"Files: **{len(files)}**",
        "",
    ]
    for path in files:
        metadata = metadata_by_path.get(path, {})
        lines.extend(
            [
                f"## {path.name}",
                f"**Relative path:** `{_relative_label(path, normalized_roots)}`",
                "",
                "| Metadata key | Value |",
                "|---|---|",
            ]
        )
        long_fields: List[Tuple[str, str]] = []
        if not metadata:
            lines.append("| `error` | Metadata could not be read |")
        else:
            for key, raw_value in metadata.items():
                rendered = _render_value(raw_value)
                if (
                    "template" in key.casefold()
                    or "\n" in rendered
                    or len(rendered) > 160
                ):
                    long_fields.append((str(key), rendered))
                    rendered = "See bounded block below"
                lines.append(f"| `{key}` | `{_escape_table(rendered)}` |")
        lines.append("")
        for key, rendered in long_fields:
            # Four backticks safely contain the common triple-backtick sequences
            # that can appear in chat templates.
            lines.extend([f"**{key}:**", "````text", rendered, "````", ""])
        lines.extend(["---", ""])
    return "\n".join(lines)


def write_metadata_report(
    roots: Iterable[Path],
    output_md: Path,
    *,
    progress: Optional[ProgressCallback] = None,
) -> Tuple[Path, int]:
    """Scan all GGUF headers below *roots* and atomically write Markdown."""
    normalized_roots = [Path(root).expanduser().resolve(strict=False) for root in roots]
    files = discover_gguf_files(normalized_roots)
    callback = progress or (lambda _done, _total, _name: None)
    callback(0, len(files), "Discovering GGUF files")
    metadata_by_path = read_gguf_metadata_many(files)
    for index, path in enumerate(files, start=1):
        callback(index, len(files), path.name)
    flush_gguf_metadata_cache()

    output = Path(output_md).expanduser().resolve(strict=False)
    output.parent.mkdir(parents=True, exist_ok=True)
    text = format_metadata_markdown(files, metadata_by_path, normalized_roots)
    tmp = output.with_suffix(output.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    os.replace(tmp, output)
    return output, len(files)


def scan_models(start_path: str | os.PathLike[str], output_md: str | os.PathLike[str]):
    """Backward-compatible callable used by older instructions/scripts."""
    root = Path(start_path)
    output = Path(output_md)
    print(f"Scanning GGUF metadata in: {root.resolve(strict=False)}")
    written, count = write_metadata_report([root], output)
    print(f"Done: {count} file(s) -> {written}")
    return written


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "start_path",
        nargs="?",
        default=".",
        help="Folder to scan recursively (default: current directory)",
    )
    parser.add_argument(
        "output",
        nargs="?",
        default="models_metadata.md",
        help="Markdown output path (default: models_metadata.md)",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = _parse_args()
    scan_models(args.start_path, args.output)
